trigger:
- master
- develop
- rel/*

queue: Hosted VS2017

steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- powershell: |
    .\build.cmd
  displayName: Build 
  env:
    VSTS_ACCESS_TOKEN: $(System.AccessToken)