trigger:
- master
- develop
- rel/*

queue: Hosted VS2017

steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- task: powershell@2
  displayName: Build
  inputs: 
    filePath: .\build.cmd

- task: PublishBuildArtifacts@1
  displayName: Publish Website Artifacts
  inputs:
    pathToPublish: '$(build.artifactstagingdirectory)\output'
    artifactType: container
    artifactName: Packages
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))