# Build script
init:
  - git config --global core.autocrlf true

skip_branch_with_pr: true

# Temporarily needed until curl added to PATH
# See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
# And https://github.com/appveyor/ci/issues/1431
install:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor"

# Tests
test: off

# Artifacts
artifacts:
# Static website
  - path: output

# Branches to build
branches:
  # Whitelist
  only:
    - master

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
